server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
spring:
  application:
    name: microserver-service
feign:
  okhttp:
    enabled: true
spring.cloud.n